### ISSUE TITLE
AssertionError with buildout

### ISSUE THREAD

**Issue by matejc** [miohtama/vvv#12]
I have modified "command = ..." line (in section vvv) several times, I have used virtualenv.py versions 1.7.2, 1.7.1.2 and for fun 1.6.4, there is always the same error. I am using Python 2.7.3.

buildout.cfg

```
[buildout]
unzip = true
prefer-final = true
newest = false
develop = .

eggs =
    spinrewriter [release]

parts +=
# development tools
    py
#    pyflakes
#    pep8
    sphinxbuilder
    test
    pylint
    vvv
    precommit-hooks


# =============================================================
# Prepare a python interpreter with all buildout eggs installed
# =============================================================
[py]
recipe = zc.recipe.egg
eggs = ${buildout:eggs}
extra-paths = ${buildout:directory}
dependent-scripts = true
interpreter = py


# ===============================
# Prepare syntax validation tools
# ===============================
[pyflakes]
recipe = zc.recipe.egg
scripts =
   pyflakes
eggs =
   pyflakes
entry-points = pyflakes=pkg_resources:run_script
arguments = 'pyflakes', 'pyflakes'

[pep8]
recipe = zc.recipe.egg
eggs =
   pep8
scripts =
   pep8


# ======================================
# Prepare Sphinx documentation generator
# ======================================
[sphinxbuilder]
recipe = collective.recipe.sphinxbuilder
source = ${buildout:directory}/docs
interpreter = ${buildout:directory}/bin/py


# ==========================================
# Prepare test-runner for running unit tests
# ==========================================
[test]
recipe = zc.recipe.testrunner
defaults = ['--exit-with-status', '--auto-color', '--auto-progress']
eggs =
    ${buildout:eggs}
    spinrewriter [test]


# =======================================================
# Install pylint command needed for VVV package validator
# =======================================================
[pylint]
recipe = zc.recipe.egg
eggs =
    pylint
entry-points = pylint=pylint.lint:Run
arguments = sys.argv[1:]


# ====================================
# Install VVV under Python's
# virtualenv vvv-venv in buildout root
# ====================================
[vvv]
recipe = plone.recipe.command
stop-on-error = true
location = ${buildout:directory}/vvv-venv
#update-command = true
command = wget --no-check-certificate "https://raw.github.com/pypa/virtualenv/master/virtualenv.py" && python virtualenv.py vvv-venv && . ./vvv-venv/bin/activate && cd vvv-venv && git clone git://github.com/miohtama/vvv.git && cd vvv && python setup.py develop


# =======================================
# Install git repository precommit hooks.
# =======================================
[precommit-hooks]
recipe = plone.recipe.command
stop-on-error = true
command = ${buildout:directory}/vvv-venv/bin/vvv-install-git-pre-commit-hook ${buildout:directory}/src/spinrewriter --silent
```

last lines from output of command bin/buildout:

```
...
Installing vvv.
vvv: Running 'wget --no-check-certificate "https://raw.github.com/pypa/virtualenv/master/virtualenv.py" && python virtualenv.py vvv-venv && . ./vvv-venv/bin/activate && cd vvv-venv && git clone git://github.com/miohtama/vvv.git && cd vvv && python setup.py develop'
--2012-07-03 16:43:33--  https://raw.github.com/pypa/virtualenv/master/virtualenv.py
Resolving raw.github.com (raw.github.com)... 207.97.227.243
Connecting to raw.github.com (raw.github.com)|207.97.227.243|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 108233 (106K) [text/plain]
Saving to: `virtualenv.py'

100%[======================================================================================================================================================>] 108,233      417K/s   in 0.3s    

2012-07-03 16:43:34 (417 KB/s) - `virtualenv.py' saved [108233/108233]

Traceback (most recent call last):
  File "virtualenv.py", line 2429, in <module>
    main()
  File "virtualenv.py", line 942, in main
    never_download=options.never_download)
  File "virtualenv.py", line 1043, in create_environment
    site_packages=site_packages, clear=clear))
  File "virtualenv.py", line 1198, in install_python
    site_filename_dst = change_prefix(site_filename, home_dir)
  File "virtualenv.py", line 1115, in change_prefix
    (filename, prefixes)
AssertionError: Filename /home/matej/workarea/n/spinrew4/parts/buildout/site.py does not start with any of these prefixes: ['/usr']
vvv: Non zero exit code (1) while running command.
While:
  Installing vvv.
Error: Non zero exit code (1) while running command.
```

**Comment by miohtama** [comment]
Thaks. Since version 0.4.2 (Python 2.7 compatibillity) we should work natively with buildout, but I have had not yet time to update the instructions. I'll keep you posted when the update is available (very soon).

**Comment by matejc** [comment]
I changed buildout.cfg like this

```
eggs =
    spinrewriter [release]
    vvv

parts +=
# development tools
    py
#    pyflakes
#    pep8
    sphinxbuilder
    test
    pylint
#    vvv
#    precommit-hooks
```

and creating virtualenv inside project:

```
virtualenv-2.7 .
source bin/activate
```

and then running `bin/buildout` works
