### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jsalonen** [miohtama/vvv#2]
Hi!

I would really, really, really appreciate having Windows support in `vvv`.

Is there anything I can do to help achieving that?

**Comment by miohtama** [comment]
There isn't anything preventing it in theory. Just that I don't have a Windows to test with :) I have build code base in portable manner and it should be ok'ish to run it on Windows. Also one must write installation instructions etc. for Windows. How does virtualenv work under Windows?

Try run it and tell what happens :)

**Comment by jsalonen** [comment]
Virtualenv works flawlessly under Windows, it even supports Windows PowerShell!

What I have tried so far (in PS).

Setting up project with virtualenv:

```
mkdir project1
cd project1
virtualenv venv
.\venv\Scripts\activate.ps1
```

And now, install and try out `vvv`:

```
pip install vvv
.\venv\Scripts\vvv
```

As a result, I get:

```
Traceback (most recent call last):
  File "C:\project1\venv\scripts\vvv-script.py", line 8, in <module>
    load_entry_point('vvv==0.3.0', 'console_scripts', 'vvv')()
  File "C:\project1\venv\lib\site-packages\setuptools-0.6c11-py2.7.egg\pkg_resources.py", line 318, in load_entry_point
  File "C:\project1\venv\lib\site-packages\setuptools-0.6c11-py2.7.egg\pkg_resources.py", line 2221, in load_entry_point
  File "C:\project1\venv\lib\site-packages\setuptools-0.6c11-py2.7.egg\pkg_resources.py", line 1954, in load
  File "C:\project1\venv\lib\site-packages\vvv\main.py", line 393
    options : ("Validation options file. Default is validation-options.yaml", 'option', 'o', None, None, "validation-options.yaml"
),
            ^
SyntaxError: invalid syntax
```

Edit: looking back to the issue, it seems that this problem is caused by using Python 2.7 - I don't have Python 3 available in my Windows box... I'm hoping to do this soon and will get back to this.

**Comment by miohtama** [comment]
Python 3+ required - Python 2 does not understand function argument annotations

**Comment by miohtama** [comment]
It this is unbearable problem we can backport the codebase to Python 2. There are few places where the changes must be done, but having P 2 and 3 compatible codebase is not unbearable effort, though extra work.

**Comment by jsalonen** [comment]
Ok. I woudly highly prefer having `vvv` available for Python 2, since most of my projects have dependencies to Python 2 -only packages. On the other hand I would want to push Python 3 adoption so in that sense it may be good to have `vvv` work only in it.

Summary: let's make Python 2 port only if its really trivial. Otherwise I would just like to see some sane error (like "Python 2 is not supported" instead of `SyntaxError`).

**Comment by miohtama** [comment]
I'll add Python 3 warning at least :) I'd rather push too for Python 3 adaption, though there are some non-trivial problems regarding the state of Python 3 in OS distributions. Like the fact how you start Python interpreter....

http://stackoverflow.com/questions/10162144/cross-platform-way-to-invoke-python-3-x-command

Also looks like 3to2 tool is in dead water:

https://bitbucket.org/amentajo/lib3to2

**Comment by miohtama** [comment]
There are three factors involving Python 3'ness in the codebase:

Abstract base classes (can be simply converted to normal base classes)

Python 3 specific imports (don't know if any)

plac main function annotations (can be converted to function decorators)

Use of unicode by default (can be fixed with **future** import)

It should one day worth of work to convert this both Python 2 and Python 3 compatible code base, not too much :) If I could start the project from the scratch I would do this from the very beginning. I was not aware that Python 3 is still largerly threaded as a second class citizen in various package managers.

**Comment by jsalonen** [comment]
Thanks! Warning would be really nice!

And yes, I  too want to push the adoption, but at the moment I just need to get stuff done. It's just horrible how hard it is to run 2 and 3 in parallel ...

**Comment by miohtama** [comment]
I started to do the porting work. Not yet there, but looks like it is doable quite easily.

**Comment by jsalonen** [comment]
That's of course awesome!

I there is anything I can do for you, please let me know.

**Comment by jsalonen** [comment]
Have you made any progress? I have to say I got a little excited once you announced about the porting :) Again, if I can be of any help, let me know.

**Comment by miohtama** [comment]
The trunk version "works" in Python 2. There are still problems with failing tests which I have not tried yet.

You could try what does trunk says on your local Windows + Python 2 combo.

BTW been on holiday, so no progress.

Trunk instructions: http://miohtama.github.com/vvv/develop.html#setting-up-development-environment (just use any Python version + virtualenv)

**Comment by miohtama** [comment]
Ok, now all unit tests pass on Python 2.7 - please feel free to trying out Github trunk version on Windows and tell me how it plays out:

http://miohtama.github.com/vvv/installation.html#installing-trunk-version

**Comment by miohtama** [comment]
0.4.0 has been released with Python 2.7 compatibiltiy.

0.4.1 will be the version with Windows fixes if you can test and provide patches and necessary documentation :)

**Comment by jsalonen** [comment]
Nice job!

I'm getting farther. Installed 0.4.0 with `pip install -upgrade vvv`.

Create `validation-options.yaml` under my project with:

```
tabs:
    enable: false
```

When I run `vvv .` I get:

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\vvv-script.py", line 9, in <module>
    load_entry_point('vvv==0.4.0', 'console_scripts', 'vvv')()
  File "C:\Python27\lib\site-packages\vvv\main.py", line 436, in entry_point
    exit_code = plac.call(main)
  File "C:\Python27\lib\site-packages\plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "C:\Python27\lib\site-packages\plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "C:\Python27\lib\site-packages\vvv\main.py", line 427, in main
    sys.exit(vvv.run())
  File "C:\Python27\lib\site-packages\vvv\main.py", line 363, in run
    self.read_config()
  File "C:\Python27\lib\site-packages\vvv\main.py", line 219, in read_config
    if os.path.exists(self.files):
  File "C:\Python27\lib\genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Same error under a virtualenv.

I'm very busy right now. Hope to get back on this later.

**Comment by miohtama** [comment]
Ok, I think I can squeeze this bug.

**Comment by miohtama** [comment]
Released 0.4.1 to address the issue.

**Comment by jsalonen** [comment]
Testing with `0.4.1`:

Forgot to mention earlier that `ghettoci` doesn't work, though its Python 3 -only anyway:

```
Installing collected packages: vvv
  Running setup.py install for vvv
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    Installing vvv-validate-rst-script.py script to C:\work\vvv\venv-vvv\Scripts
    ...
    SyntaxError: ('invalid syntax', ('C:\\work\\vvv\\venv-vvv\\Lib\\site-packages
    \\ghettoci\\main.py', 321, 21, 'class Repo(metaclass=ABCMeta):\n'))
```

Also when running `vvv .` I still get:

```
Traceback (most recent call last):
  File "C:\work\vvv\venv-vvv\Scripts\vvv-script.py", line 8, in <module>
    load_entry_point('vvv==0.4.1', 'console_scripts', 'vvv')()
  ...
  File "C:\work\vvv\venv-vvv\lib\site-packages\vvv\main.py", line 363, in run
    self.read_config()
  File "C:\work\vvv\venv-vvv\lib\site-packages\vvv\main.py", line 210, in read_config
    if os.path.exists(self.options):
  File "C:\work\vvv\venv-vvv\lib\genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

Any ideas? I'd be glad to try more.

**Comment by miohtama** [comment]
I'll first clear ghettoci packaking problems. It looks like it never finds option file, but it should have graceful fallback around that. More like wat might happen that it it finds option file, but for some reason skips it.

Can you please have a dummy directory structure explained how you have placed your files and how you run vvv? I think there must be some case which has not been covered yet.

**Comment by jsalonen** [comment]
Figured out the problem: I had mistyped `validation-files.yaml` (was: `validation-files.yml`) :| So basically you get `TypeError` when that file is not found.

Would it be possible to have a more informative message? The same applies for missing `validation-options.yaml` - if it's missing you get `TypeError` (which doesn't help a lot).

Related idea for future releases: ability to generate/scaffold option files based on given settings/template.

As a last note: I now confirm that VVV 0.4.1 works on Windows 7 with Python 2.7.2 and has been successfully integrated into my toolchain.

As such, this issue may be closed.

**Comment by miohtama** [comment]
Could you write installation instructions for Windows and then we can claim Windows support? :)

(I have no idea how virtualenv and such work on Windows)

**Comment by jsalonen** [comment]
Sure!

Add something like this under section "Installing locally using virtualenv":

## Windows 7

Tested on Windows 7 with Python 2.7

Make sure `virtualenv` is installed:

```
pip install virtualenv
```

Installing prerequisites by creating vvv-venv virtualenv in your home folder:

```
cd %HOME%
virtualenv vvv-venv
.\venv-vvv\Scripts\activate
pip install vvv
```

Or if you are using PowerShell:

```
cd ~
virtualenv vvv-env
.\venv-vvv\Scripts\activate.ps1
pip install vvv
```

**Comment by miohtama** [comment]
BTW

You can directly edit the doc here in Github's web interface:

https://github.com/miohtama/vvv/blob/master/docs/source/installation.rst

It will generate a pull request.

Pretty please? :)

**Comment by jsalonen** [comment]
Wow didn't know about that! Thanks for teaching!

Updated and added a pull request: https://github.com/miohtama/vvv/pull/11
